version: '2'

services:
  client2:
    image: pytorrent:latest
    container_name: pytorrent_2
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
    volumes:
      - ./docker_container_configs/conf_1.ini:/opt/pyTorrent/conf/configs.ini
      - ./docker_container_configs/zone_1.txt:/opt/pyTorrent/discover/zone.txt
    entrypoint: python main.py
  client3:
    image: pytorrent:latest
    container_name: pytorrent_3
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
    volumes:
      - ./docker_container_configs/conf_2.ini:/opt/pyTorrent/conf/configs.ini
      - ./docker_container_configs/zone_2.txt:/opt/pyTorrent/discover/zone.txt
    entrypoint: python main.py
  client4:
    image: pytorrent:latest
    container_name: pytorrent_4
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
    volumes:
      - ./docker_container_configs/conf_3.ini:/opt/pyTorrent/conf/configs.ini
      - ./docker_container_configs/zone_3.txt:/opt/pyTorrent/discover/zone.txt
    entrypoint: python main.py

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.1.1